### ISSUE TITLE
how do it use the init during battle?

### ISSUE THREAD

**Issue by ghosttea-tech** [agehring80/CheatEngine#2]
![image](https://github.com/agehring80/CheatEngine/assets/174709643/0ef775ed-2709-4d78-bad2-c496daa0868a)
i click on it during battle but nothing happen? only able to use auto onces

**Comment by agehring80** [comment]
Hi,

first of all, cool that someone uses my scripts. :-)
Shows me that the old cool games are not forgotten.
Let me try to explain the way I implemented it.

Init is a piece of code that initializes the important variables (needed for the functions.)
It is not a checkbox or something that you can use as action or something.
So the checkbox gets not checked. Same by the functions.
You need to run the init once, and you need to do it in the BattleScreen,
because all other functions depends on the init variables.

If you encounter some further issues or need help,
feel free to ask again, please.

Have fun !

**Comment by ghosttea-tech** [comment]
you mention that i need to run the init once, and you need to do it in the BattleScreen, how do i run it?

**Comment by agehring80** [comment]
Hi.

First of all, I updated the Script to run with ja2-stracciatella_0.21.0-git+61938e1_win-msvc64-142
The script needed adjusted offsets for the newest version 0.21.0.

Can you try again, please ?

Follow this steps.
1. Run the game and enter the BattleScreen.
2. Click the checkbox for init. (No immideate feedback, I agree that this is confusing, but it works.)
           You need to do it only once !
3. The first hand should be empty, because existing items gets only replaced if it is one of the available ones by cheat shortcuts.
4. Press Crtl+F1 to see if it is working.
5. The auto scripts gets checked, if clicked.

Hope it works...

![grafik](https://github.com/agehring80/CheatEngine/assets/20336118/d2d6efb5-445a-42b9-ad7f-964523ced42a)

**Comment by ghosttea-tech** [comment]
its the battlescreen has to be during combat?

**Comment by agehring80** [comment]
Hello :-)

no, doesn't matter if you're in combat or not.

In case it's not working, let us check some prequesits.

1. Are you on the latest JA2 Straciatella improvement ?
https://github.com/ja2-stracciatella/ja2-stracciatella/releases/download/v0.21.0/ja2-stracciatella_0.21.0-git+61938e1_win-msvc64-142.exe

2. Do you use the newest CheatEngine file (updated about 12h ago) ?
https://github.com/agehring80/CheatEngine/blob/master/JaggedAlliance2/JA2_Stracciatella_x64.CT

3. Attach to the right process with CheatEngine
![grafik](https://github.com/agehring80/CheatEngine/assets/20336118/129d7036-0ce7-4956-ba75-ec59b370fdbe)

4. The soldier addresses should be visible then... And they are probabbly different than mine. Click Init
![grafik](https://github.com/agehring80/CheatEngine/assets/20336118/36d993b8-daa2-4df0-aaf2-be950402c458)

5. Select the soldier you want to equip
![grafik](https://github.com/agehring80/CheatEngine/assets/20336118/b377da69-8315-464d-940b-349304a10bfa)

5b. The hand should be empty !!!

6. Press Crtl+F1 and the selected soldier should get the AR Rifle
![grafik](https://github.com/agehring80/CheatEngine/assets/20336118/9fc41ea2-0da6-4fd0-b240-7c6c309f0b9f)

Can you tell me exactly what is working and what's not ?
If it is not working, we can get in touch and do it together with a remote tool... TeamViewer or something else.

Have fun !

**Comment by ghosttea-tech** [comment]
thank you i manage to get it running based on your input thank you

**Comment by agehring80** [comment]
Hi. Nice !

Have fun !
